import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen">
      <body className="flex lg:flex-row flex-col bg-gray-800">
        <Sidebar />
        <div className=" w-full m-5 p-5 border-2 rounded-lg border-current bg-gray-500">
        {children}
        </div>
      </body>
    </html>
  );
}
