import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import ResponsiveSidebar from "./components/ResponsiveSidebar";
import { isAuthenticatedUser } from "./api/api";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const status = isAuthenticatedUser();
  if(!status) {
    const router = useRouter();
    router.push("/login");
  }


  return (
    <html lang="en">
      <body className="flex  bg-[#c9e4de]">
        <div className="hidden md:flex">
          <Sidebar />
        </div>
        <div className="md:hidden">
          <ResponsiveSidebar />
        </div>
        <div className=" w-full lg:m-5 p-5 border-4 shadow-lg rounded-lg border-gray-500 bg-[#faedcb]">
        {children}
        </div>
      </body>
    </html>
  );
}
