import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { isAuthenticated } from "./api/api";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let user = false;
  if (isAuthenticated()){
    user = true;
  }

  if (!user){
    router.push('/login');
  }

  return (
    <html lang="en">
      <body className="flex  bg-gray-300">
        <Sidebar />
        <div className=" w-full m-5 p-5 border-4 shadow-lg rounded-lg border-white bg-gray-600">
        {children}
        </div>
      </body>
    </html>
  );
}
